name: image_upload_flutter_firebase
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7
  image_picker: ^1.1.2
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
