// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqu3Qq8B07RIi__YMEvsUSryzDdX2kmA',
    appId: '1:527043072965:web:9622b322c8d60cb723f1ac',
    messagingSenderId: '527043072965',
    projectId: 'image-upload-flutter-firebase7',
    authDomain: 'image-upload-flutter-firebase7.firebaseapp.com',
    storageBucket: 'image-upload-flutter-firebase7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIakOb_IElp_a30jMI2wW9ozSU1GOKi3w',
    appId: '1:527043072965:android:0a3aa3535ba4e95a23f1ac',
    messagingSenderId: '527043072965',
    projectId: 'image-upload-flutter-firebase7',
    storageBucket: 'image-upload-flutter-firebase7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-D2e1oiGfjGju9zfU2Xrp0ZeDOZ1u_A',
    appId: '1:527043072965:ios:6fe627ec68bf00b323f1ac',
    messagingSenderId: '527043072965',
    projectId: 'image-upload-flutter-firebase7',
    storageBucket: 'image-upload-flutter-firebase7.appspot.com',
    iosBundleId: 'com.example.imageUploadFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-D2e1oiGfjGju9zfU2Xrp0ZeDOZ1u_A',
    appId: '1:527043072965:ios:6fe627ec68bf00b323f1ac',
    messagingSenderId: '527043072965',
    projectId: 'image-upload-flutter-firebase7',
    storageBucket: 'image-upload-flutter-firebase7.appspot.com',
    iosBundleId: 'com.example.imageUploadFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbqu3Qq8B07RIi__YMEvsUSryzDdX2kmA',
    appId: '1:527043072965:web:34cf77e5009ea6a423f1ac',
    messagingSenderId: '527043072965',
    projectId: 'image-upload-flutter-firebase7',
    authDomain: 'image-upload-flutter-firebase7.firebaseapp.com',
    storageBucket: 'image-upload-flutter-firebase7.appspot.com',
  );

}